[package]
name = "pino_argparse"
version = "0.1.0"
authors = ["pinosaur"]
description = "a tiny argparsing library"
repository = "https://github.com/MrPicklePinosaur/pino_argparse"
edition = "2021"

[dependencies]

