[package]
name = "pino_argparse"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"
authors = ["MrPicklePinosaur"]
description = "a tiny argparsing library"
repository = "https://github.com/MrPicklePinosaur/pino_argparse"

[dependencies]

